apiVersion: v1
kind: Service
metadata:
  name: crew-demo-postgres-rw
spec:
  selector:
    app.kubernetes.io/name: crew-demo-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
